apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: logging
spec:
  replicas: 5
  template:
    metadata:
      labels:
      app: web
      spec:
        containers:
          - name: apache
            image: httpd
            ports:
              - containerPort: 80
            volumeMounts:
              - name: log
                mountPath: /var/log/apache2
      volumes:
        - name: log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: logging
  labels:
   app: web
spec:
 ports:
    - port: 80
      protocol: TCP
      targetPort: 80
 selector:
   app: web

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: logging
  labels:
    app: web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    -
      http:
        paths:
          -
            backend:
              serviceName:  webserver
              servicePort: 80
            path: /web