apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: logging
  labels:
    k8s-app: web

spec:
  serviceName: webserver-deployment
  replicas: 5
  selector:
    matchLabels:
      k8s-app: webserver-deployment

  template:
    metadata:
      labels:
        k8s-app: web

    spec:
      containers:
        - image:httpd
          name: apache
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 80
          volumeMounts:
            - name: log
              mountPath: /var/log/apache2

      volumes:
        - name: log
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: logging
  labels:
   app: web
spec:
 ports:
    - port: 80
      protocol: TCP
      targetPort: 80
 selector:
   app: web

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: logging
  labels:
    app: web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    -
      http:
        paths:
          -
            backend:
              serviceName:  webserver
              servicePort: 80
            path: /web